"""Model A training: answer verification and question generation."""

from __future__ import annotations

import argparse
import os
import re
import time
from collections import Counter
from typing import Any, Iterable, Optional

import joblib
import numpy as np
import pandas as pd
from scipy import sparse
from sklearn.calibration import CalibratedClassifierCV
from sklearn.cluster import KMeans
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score, silhouette_score, roc_auc_score, average_precision_score, brier_score_loss
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import ComplementNB
from sklearn.preprocessing import LabelEncoder
from sklearn.semi_supervised import LabelSpreading
from sklearn.svm import LinearSVC
from sklearn.metrics.pairwise import cosine_similarity

try:
    from xgboost import XGBClassifier
except Exception:  # pragma: no cover - optional dependency path
    XGBClassifier = None

try:
    from preprocessing import build_ohe_vectorizer, clean_text, extract_lexical_features
    import nlp_metrics
except ImportError:  # pragma: no cover
    from .preprocessing import build_ohe_vectorizer, clean_text, extract_lexical_features
    from . import nlp_metrics

RANDOM_STATE = 42


def load_processed(data_dir: str) -> dict[str, Any]:
    """Load processed sparse matrices, labels, and metadata.

    Args:
        data_dir: Directory generated by ``preprocess_pipeline``.

    Returns:
        Dictionary with train/val/test matrices and labels.
    """
    try:
        return {
            "X_train": sparse.load_npz(os.path.join(data_dir, "X_train_combined.npz")),
            "X_val": sparse.load_npz(os.path.join(data_dir, "X_val_combined.npz")),
            "X_test": sparse.load_npz(os.path.join(data_dir, "X_test_combined.npz")),
            "X_train_ohe": sparse.load_npz(os.path.join(data_dir, "X_train_ohe.npz")),
            "X_val_ohe": sparse.load_npz(os.path.join(data_dir, "X_val_ohe.npz")),
            "y_train": np.load(os.path.join(data_dir, "y_train.npy")),
            "y_val": np.load(os.path.join(data_dir, "y_val.npy")),
            "train_expanded": pd.read_csv(os.path.join(data_dir, "train_expanded.csv.gz")),
            "val_expanded": pd.read_csv(os.path.join(data_dir, "val_expanded.csv.gz")),
        }
    except Exception as exc:
        raise RuntimeError(f"Failed to load processed data from {data_dir}: {exc}") from exc


def evaluate_binary_model(name: str, y_true: np.ndarray, y_pred: np.ndarray, y_proba: Optional[np.ndarray] = None) -> dict[str, Any]:
    """Compute and print core Model A classification metrics.

    Args:
        name: Model name.
        y_true: Ground-truth binary labels.
        y_pred: Predicted binary labels.
        y_proba: Optional probability of the positive class.

    Returns:
        Metrics dictionary.
    """
    metrics = {
        "model": name,
        "accuracy": accuracy_score(y_true, y_pred),
        "macro_f1": f1_score(y_true, y_pred, average="macro", zero_division=0),
        "precision": precision_score(y_true, y_pred, average="macro", zero_division=0),
        "recall": recall_score(y_true, y_pred, average="macro", zero_division=0),
        "exact_match": accuracy_score(y_true, y_pred),
        "confusion_matrix": confusion_matrix(y_true, y_pred),
    }
    if y_proba is not None:
        metrics["avg_positive_probability"] = float(np.mean(y_proba))
        try:
            metrics["roc_auc"] = float(roc_auc_score(y_true, y_proba))
            metrics["pr_auc"] = float(average_precision_score(y_true, y_proba))
            metrics["brier_score"] = float(brier_score_loss(y_true, y_proba))
        except Exception:
            metrics["roc_auc"] = 0.0
            metrics["pr_auc"] = 0.0
            metrics["brier_score"] = 0.0
    else:
        metrics["roc_auc"] = 0.0
        metrics["pr_auc"] = 0.0
        metrics["brier_score"] = 0.0
        
    print(f"\n{name}")
    print(
        f"Accuracy: {metrics['accuracy']:.4f} | Macro F1: {metrics['macro_f1']:.4f} | "
        f"Precision: {metrics['precision']:.4f} | Recall: {metrics['recall']:.4f} | "
        f"Exact Match: {metrics['exact_match']:.4f}"
    )
    print(metrics["confusion_matrix"])
    print(classification_report(y_true, y_pred, target_names=["incorrect_option", "correct_option"], zero_division=0))
    return metrics


def _save_model(model: Any, model_dir: str, filename: str) -> None:
    """Persist a trained model immediately."""
    try:
        os.makedirs(model_dir, exist_ok=True)
        joblib.dump(model, os.path.join(model_dir, filename))
        print(f"Saved {filename}")
    except Exception as exc:
        raise RuntimeError(f"Failed to save {filename}: {exc}") from exc


def train_logistic_regression(X_train: sparse.spmatrix, y_train: np.ndarray, model_dir: str) -> LogisticRegression:
    """Train Logistic Regression on combined sparse features.

    Args:
        X_train: Combined OHE plus lexical feature matrix.
        y_train: Binary labels.
        model_dir: Destination directory.

    Returns:
        Trained LogisticRegression.
    """
    model = LogisticRegression(
        C=1.0,
        solver="saga",
        max_iter=1000,
        n_jobs=-1,
        class_weight="balanced",
        random_state=RANDOM_STATE,
    )
    model.fit(X_train, y_train)
    _save_model(model, model_dir, "logistic_regression.pkl")
    return model


def train_svm(X_train: sparse.spmatrix, y_train: np.ndarray, model_dir: str) -> CalibratedClassifierCV:
    """Train calibrated LinearSVC so probability scores are available.

    Args:
        X_train: Combined sparse feature matrix.
        y_train: Binary labels.
        model_dir: Destination directory.

    Returns:
        Calibrated SVM classifier.
    """
    base = LinearSVC(C=1.0, max_iter=2000, class_weight="balanced", random_state=RANDOM_STATE)
    model = CalibratedClassifierCV(base, cv=3)
    model.fit(X_train, y_train)
    _save_model(model, model_dir, "linear_svc_calibrated.pkl")
    return model


def _question_type(question: str) -> str:
    """Infer a simple question type label from the first word."""
    first = clean_text(question).split()
    if not first:
        return "other"
    return first[0] if first[0] in {"what", "who", "where", "when", "why", "how"} else "other"


def train_question_type_nb(
    X_train_ohe: sparse.spmatrix,
    train_expanded: pd.DataFrame,
    X_val_ohe: sparse.spmatrix,
    val_expanded: pd.DataFrame,
    model_dir: str,
) -> dict[str, Any]:
    """Train ComplementNB for question-type classification.

    Args:
        X_train_ohe: Non-negative OHE training features.
        train_expanded: Expanded training metadata.
        X_val_ohe: Non-negative OHE validation features.
        val_expanded: Expanded validation metadata.
        model_dir: Destination directory.

    Returns:
        Dictionary containing model, encoder, and validation metrics.
    """
    encoder = LabelEncoder()
    train_types = train_expanded["question"].map(_question_type)
    val_types = val_expanded["question"].map(_question_type)
    encoder.fit(pd.concat([train_types, val_types], ignore_index=True))
    y_train_type = encoder.transform(train_types)
    y_val_type = encoder.transform(val_types)
    model = ComplementNB(alpha=0.1)
    model.fit(abs(X_train_ohe), y_train_type)
    preds = model.predict(abs(X_val_ohe))
    metrics = {
        "model": "ComplementNB question type",
        "accuracy": accuracy_score(y_val_type, preds),
        "macro_f1": f1_score(y_val_type, preds, average="macro", zero_division=0),
        "labels": encoder.classes_.tolist(),
    }
    _save_model({"model": model, "encoder": encoder, "metrics": metrics}, model_dir, "complement_nb_question_type.pkl")
    print(f"\nComplementNB question-type accuracy: {metrics['accuracy']:.4f} | Macro F1: {metrics['macro_f1']:.4f}")
    return {"model": model, "encoder": encoder, "metrics": metrics}


def soft_voting_predict(models: Iterable[Any], X: sparse.spmatrix) -> np.ndarray:
    """Average positive-class probabilities from classifiers.

    Args:
        models: Iterable of fitted classifiers exposing ``predict_proba``.
        X: Feature matrix.

    Returns:
        Positive-class probability vector.
    """
    probabilities = [model.predict_proba(X)[:, 1] for model in models]
    return np.mean(np.vstack(probabilities), axis=0)


def train_hard_voting(lr: Any, svm: Any, X_val: sparse.spmatrix, y_val: np.ndarray) -> dict[str, Any]:
    """Evaluate a hard-voting ensemble from LR and SVM predictions.

    Args:
        lr: Fitted LogisticRegression.
        svm: Fitted calibrated SVM.
        X_val: Validation matrix.
        y_val: Validation labels.

    Returns:
        Metrics dictionary.
    """
    votes = np.vstack([lr.predict(X_val), svm.predict(X_val)])
    preds = (np.mean(votes, axis=0) >= 0.5).astype(int)
    return evaluate_binary_model("Hard Voting Ensemble", y_val, preds)


def train_stacking(X_train: sparse.spmatrix, y_train: np.ndarray, model_dir: str, max_rows: int = 30000) -> Optional[StackingClassifier]:
    """Train a compact stacking ensemble for the rubric extension.

    Args:
        X_train: Combined feature matrix.
        y_train: Binary labels.
        model_dir: Destination directory.
        max_rows: Maximum rows used for runtime control.

    Returns:
        Fitted stacking classifier, or None if training fails.
    """
    rows = np.arange(X_train.shape[0])
    if X_train.shape[0] > max_rows:
        _, rows = train_test_split(rows, test_size=max_rows, random_state=RANDOM_STATE, stratify=y_train)
    estimators = [
        (
            "lr",
            LogisticRegression(
                C=0.7,
                solver="saga",
                max_iter=500,
                n_jobs=-1,
                class_weight="balanced",
                random_state=RANDOM_STATE,
            ),
        ),
        ("svm", CalibratedClassifierCV(LinearSVC(C=0.7, max_iter=1200, class_weight="balanced", random_state=RANDOM_STATE), cv=3)),
    ]
    model = StackingClassifier(
        estimators=estimators,
        final_estimator=LogisticRegression(max_iter=500, class_weight="balanced", random_state=RANDOM_STATE),
        cv=3,
        n_jobs=-1,
    )
    model.fit(X_train[rows], y_train[rows])
    _save_model(model, model_dir, "stacking_ensemble.pkl")
    return model


def train_xgboost_optional(X_train: sparse.spmatrix, y_train: np.ndarray, model_dir: str, max_rows: int = 30000) -> Optional[Any]:
    """Train optional XGBoost if installed and save it.

    Args:
        X_train: Sparse feature matrix.
        y_train: Binary labels.
        model_dir: Destination directory.
        max_rows: Maximum rows for Colab-friendly runtime.

    Returns:
        Trained XGBoost classifier or None.
    """
    if XGBClassifier is None:
        print("XGBoost is unavailable; skipping optional model.")
        return None
    rows = np.arange(X_train.shape[0])
    if X_train.shape[0] > max_rows:
        _, rows = train_test_split(rows, test_size=max_rows, random_state=RANDOM_STATE, stratify=y_train)
    model = XGBClassifier(
        n_estimators=120,
        max_depth=4,
        learning_rate=0.08,
        subsample=0.9,
        colsample_bytree=0.8,
        scale_pos_weight=3.0,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=2,
    )
    model.fit(X_train[rows], y_train[rows])
    _save_model(model, model_dir, "xgboost_optional.pkl")
    return model


def run_unsupervised_models(
    X_train: sparse.spmatrix,
    X_val: sparse.spmatrix,
    y_val: np.ndarray,
    model_dir: str,
    sample_rows: int = 5000,
) -> dict[str, Any]:
    """Train KMeans and GMM after TruncatedSVD and report cluster diagnostics.

    Args:
        X_train: Training matrix.
        X_val: Validation matrix.
        y_val: Validation labels.
        model_dir: Destination directory.
        sample_rows: Maximum validation rows for silhouette calculations.

    Returns:
        Metrics dictionary for unsupervised models.
    """
    svd = TruncatedSVD(n_components=50, random_state=RANDOM_STATE)
    X_train_svd = svd.fit_transform(X_train)
    X_val_svd = svd.transform(X_val)
    kmeans = KMeans(n_clusters=4, random_state=RANDOM_STATE, n_init=10)
    kmeans.fit(X_train_svd)
    sample_n = min(sample_rows, X_val_svd.shape[0])
    val_sample = X_val_svd[:sample_n]
    val_labels = y_val[:sample_n]
    clusters = kmeans.predict(val_sample)
    sil = float(silhouette_score(val_sample, clusters)) if len(set(clusters)) > 1 else 0.0
    sizes = dict(Counter(clusters))
    purity_parts = []
    for cluster in sorted(sizes):
        mask = clusters == cluster
        purity_parts.append(np.max(np.bincount(val_labels[mask], minlength=2)) / max(1, int(mask.sum())))
    purity = float(np.mean(purity_parts)) if purity_parts else 0.0
    gmm = GaussianMixture(n_components=4, random_state=RANDOM_STATE, covariance_type="diag")
    gmm.fit(X_train_svd[: min(30000, X_train_svd.shape[0])])
    gmm_clusters = gmm.predict(val_sample)
    gmm_sil = float(silhouette_score(val_sample, gmm_clusters)) if len(set(gmm_clusters)) > 1 else 0.0
    _save_model({"svd": svd, "kmeans": kmeans, "gmm": gmm}, model_dir, "unsupervised_svd_kmeans_gmm.pkl")
    print(f"\nKMeans silhouette: {sil:.4f} | cluster sizes: {sizes} | purity estimate: {purity:.4f}")
    print(f"GMM silhouette: {gmm_sil:.4f}")
    return {"kmeans_silhouette": sil, "cluster_sizes": sizes, "purity_estimate": purity, "gmm_silhouette": gmm_sil}


def run_semi_supervised(
    X_train: sparse.spmatrix,
    y_train: np.ndarray,
    X_val: sparse.spmatrix,
    y_val: np.ndarray,
    supervised_f1: float,
    model_dir: str,
    max_rows: int = 8000,
) -> dict[str, Any]:
    """Train LabelSpreading on SVD features with 10% labels and compare to LR.

    Args:
        X_train: Training matrix.
        y_train: Training labels.
        X_val: Validation matrix.
        y_val: Validation labels.
        supervised_f1: Baseline supervised LR macro F1.
        model_dir: Destination directory.
        max_rows: Maximum training rows for graph-based runtime control.

    Returns:
        Semi-supervised metrics dictionary.
    """
    rows = np.arange(X_train.shape[0])
    if X_train.shape[0] > max_rows:
        _, rows = train_test_split(rows, test_size=max_rows, random_state=RANDOM_STATE, stratify=y_train)
    svd = TruncatedSVD(n_components=50, random_state=RANDOM_STATE)
    X_small = svd.fit_transform(X_train[rows])
    y_small = y_train[rows].copy()
    rng = np.random.default_rng(RANDOM_STATE)
    labeled_mask = rng.random(len(y_small)) < 0.10
    semi_labels = np.where(labeled_mask, y_small, -1)
    model = LabelSpreading(kernel="knn", n_neighbors=7, max_iter=30)
    model.fit(X_small, semi_labels)
    X_val_svd = svd.transform(X_val[: min(max_rows, X_val.shape[0])])
    y_val_small = y_val[: X_val_svd.shape[0]]
    preds = model.predict(X_val_svd)
    semi_f1 = f1_score(y_val_small, preds, average="macro", zero_division=0)
    _save_model({"svd": svd, "model": model}, model_dir, "label_spreading.pkl")
    print(f"\nSemi-supervised LabelSpreading Macro F1: {semi_f1:.4f} vs supervised LR F1: {supervised_f1:.4f}")
    return {"semi_supervised_f1": float(semi_f1), "supervised_lr_f1": float(supervised_f1)}


def _sentence_split(article: str) -> list[str]:
    """Split article into rough sentences."""
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", str(article)) if s.strip()]


def _extract_subject_predicate(sentence: str) -> tuple[str, str]:
    """Heuristically split a sentence into (subject, predicate).

    The subject is taken as the first word (usually a proper noun or pronoun).
    The predicate is everything that follows.

    Args:
        sentence: A declarative sentence (no trailing punctuation expected).

    Returns:
        (subject, predicate) pair; predicate may be empty for single-word input.
    """
    words = sentence.strip().split()
    if not words:
        return ("", sentence)
    subject = words[0]
    predicate = " ".join(words[1:]) if len(words) > 1 else ""
    return subject, predicate


def _to_base_form(verb: str) -> str:
    """Approximate base form of a verb by stripping common inflections.

    This is a simple rule-based approach (no NLP library required).

    Args:
        verb: An inflected verb string.

    Returns:
        Approximate base form.
    """
    # Common irregular endings handled first
    irregulars = {
        "visited": "visit", "borrowed": "borrow", "gave": "give",
        "went": "go", "came": "come", "saw": "see", "read": "read",
        "was": "be", "were": "be", "had": "have", "did": "do",
        "got": "get", "took": "take", "made": "make", "said": "say",
        "told": "tell", "found": "find", "left": "leave", "kept": "keep",
    }
    v = verb.lower()
    if v in irregulars:
        return irregulars[v]
    # Strip -ed (visited → visit, borrowed → borrow)
    if v.endswith("ed") and len(v) > 4:
        # double consonant: stopped → stop
        if len(v) > 5 and v[-3] == v[-4]:
            return v[:-3]
        return v[:-2]
    # Strip -ing (visiting → visit)
    if v.endswith("ing") and len(v) > 5:
        return v[:-3]
    # Strip -s (visits → visit)
    if v.endswith("s") and len(v) > 3 and not v.endswith("ss"):
        return v[:-1]
    return v


def _make_template(sentence: str) -> list[str]:
    """Create grammatically correct Wh-word questions from a declarative sentence.

    FIX: Produces proper "What did [subject] [base-verb] ...?" constructions
    instead of the broken "What [tail]?" pattern from the original.

    Args:
        sentence: A complete declarative sentence.

    Returns:
        List of candidate question strings (deduplicated).
    """
    cleaned = sentence.strip().rstrip(".!?")
    words = cleaned.split()
    if not words:
        return []

    subject, predicate = _extract_subject_predicate(cleaned)
    pred_words = predicate.split()
    lowered = cleaned.lower()
    tokens = set(clean_text(lowered).split())

    questions: list[str] = []

    if pred_words:
        base_verb = _to_base_form(pred_words[0])
        rest = " ".join(pred_words[1:]) if len(pred_words) > 1 else ""
        # "What did Sara visit after school?" / "What did Sara borrow?"
        if rest:
            questions.append(f"What did {subject} {base_verb} {rest}?")
        else:
            questions.append(f"What did {subject} {base_verb}?")
    else:
        questions.append(f"What is {subject}?")

    person_refs = {
        "he", "she", "they", "mr", "mrs", "ms", "teacher", "student",
        "boy", "girl", "man", "woman", "her", "his", "their",
    }
    location_refs = {
        "school", "city", "room", "house", "park", "country", "village",
        "street", "library", "museum", "hospital", "store", "market",
    }
    time_refs = {
        "today", "yesterday", "tomorrow", "morning", "evening", "night",
        "year", "month", "day", "week", "monday", "tuesday", "wednesday",
        "thursday", "friday", "saturday", "sunday",
    }

    if tokens.intersection(person_refs):
        if pred_words:
            questions.append(f"Who {pred_words[0]} {' '.join(pred_words[1:])}?".strip())
    if tokens.intersection(location_refs):
        questions.append(f"Where did {subject} go?")
    if tokens.intersection(time_refs):
        questions.append(f"When did {subject} do this?")

    # Deduplicate preserving order
    seen: set[str] = set()
    unique: list[str] = []
    for q in questions:
        q = q.strip()
        if q and q not in seen:
            seen.add(q)
            unique.append(q)
    return unique


def generate_questions(article: str, correct_answer: str) -> list[tuple[str, float]]:
    """Generate template-based questions ranked by OHE cosine similarity.

    Args:
        article: Reading passage.
        correct_answer: Correct answer phrase used to rank sentence relevance.

    Returns:
        Ranked list of ``(question_text, score)`` tuples.
    """
    sentences = _sentence_split(article)
    if not sentences:
        return [("What is the main idea of the passage?", 0.0)]
    vectorizer = build_ohe_vectorizer(max_features=5000)
    try:
        matrix = vectorizer.fit_transform(sentences + [correct_answer])
        scores = cosine_similarity(matrix[:-1], matrix[-1]).ravel()
    except Exception:
        scores = np.zeros(len(sentences), dtype=float)
    ranked_sentence_idx = np.argsort(scores)[::-1][:3]
    candidates: list[tuple[str, float]] = []
    for idx in ranked_sentence_idx:
        for question in _make_template(sentences[int(idx)]):
            candidates.append((question, float(scores[int(idx)])))
    if not candidates:
        candidates.append(("What is supported by the passage?", 0.0))
    return sorted(candidates, key=lambda item: item[1], reverse=True)


def train_all(data_dir: str, model_dir: str, skip_slow: bool = False) -> pd.DataFrame:
    """Train all Model A components and save artifacts.

    Args:
        data_dir: Processed data directory.
        model_dir: Model output directory.
        skip_slow: Skip slower optional models for quick checks.

    Returns:
        Comparison table as a DataFrame.
    """
    data = load_processed(data_dir)
    start = time.time()
    lr = train_logistic_regression(data["X_train"], data["y_train"], model_dir)
    lr_proba = lr.predict_proba(data["X_val"])[:, 1]
    lr_metrics = evaluate_binary_model("Logistic Regression", data["y_val"], (lr_proba >= 0.5).astype(int), lr_proba)

    svm = train_svm(data["X_train"], data["y_train"], model_dir)
    svm_proba = svm.predict_proba(data["X_val"])[:, 1]
    svm_metrics = evaluate_binary_model("Calibrated LinearSVC", data["y_val"], (svm_proba >= 0.5).astype(int), svm_proba)

    nb_bundle = train_question_type_nb(data["X_train_ohe"], data["train_expanded"], data["X_val_ohe"], data["val_expanded"], model_dir)
    soft_proba = soft_voting_predict([lr, svm], data["X_val"])
    soft_metrics = evaluate_binary_model("Soft Voting Ensemble", data["y_val"], (soft_proba >= 0.5).astype(int), soft_proba)
    hard_metrics = train_hard_voting(lr, svm, data["X_val"], data["y_val"])

    extra_metrics: list[dict[str, Any]] = []
    if not skip_slow:
        stacking = train_stacking(data["X_train"], data["y_train"], model_dir)
        if stacking is not None:
            stack_proba = stacking.predict_proba(data["X_val"])[:, 1]
            extra_metrics.append(evaluate_binary_model("Stacking Ensemble", data["y_val"], (stack_proba >= 0.5).astype(int), stack_proba))
        xgb = train_xgboost_optional(data["X_train"], data["y_train"], model_dir)
        if xgb is not None:
            xgb_proba = xgb.predict_proba(data["X_val"])[:, 1]
            extra_metrics.append(evaluate_binary_model("XGBoost Optional", data["y_val"], (xgb_proba >= 0.5).astype(int), xgb_proba))
        unsup_metrics = run_unsupervised_models(data["X_train"], data["X_val"], data["y_val"], model_dir)
        semi_metrics = run_semi_supervised(data["X_train"], data["y_train"], data["X_val"], data["y_val"], lr_metrics["macro_f1"], model_dir)
    else:
        unsup_metrics, semi_metrics = {}, {}

    print("\nEvaluating generated questions for NLP metrics...")
    val_csv_path = os.path.join("data", "raw", "val.csv")
    q_bleus, q_rouges, q_meteors = [], [], []
    if os.path.exists(val_csv_path):
        val_df = pd.read_csv(val_csv_path).head(100) # subset for speed
        for _, row in val_df.iterrows():
            article = str(row.get("article", ""))
            gold_q = str(row.get("question", ""))
            if article and gold_q:
                # generate question based on first sentence as seed
                sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", article) if s.strip()]
                seed = sentences[0] if sentences else article
                gen_q_list = generate_questions(article, seed)
                gen_q = gen_q_list[0][0] if gen_q_list else ""
                
                q_bleus.append(nlp_metrics.compute_bleu(gold_q, gen_q))
                q_rouges.append(nlp_metrics.compute_rouge(gold_q, gen_q))
                q_meteors.append(nlp_metrics.compute_meteor(gold_q, gen_q))
    
    nlp_eval = {
        "question_bleu": float(np.mean(q_bleus)) if q_bleus else 0.0,
        "question_rouge": float(np.mean(q_rouges)) if q_rouges else 0.0,
        "question_meteor": float(np.mean(q_meteors)) if q_meteors else 0.0,
    }

    models = [lr_metrics, svm_metrics, hard_metrics, soft_metrics, nb_bundle["metrics"], *extra_metrics]
    table = pd.DataFrame([{k: v for k, v in row.items() if k != "confusion_matrix"} for row in models])
    table["training_wall_seconds"] = round(time.time() - start, 2)
    os.makedirs(os.path.join(model_dir), exist_ok=True)
    try:
        joblib.dump({
            "metrics": table,
            "confusion_matrix": soft_metrics["confusion_matrix"],
            "nlp_metrics": nlp_eval,
            "unsupervised_metrics": unsup_metrics,
            "semi_supervised_metrics": semi_metrics
        }, os.path.join(model_dir, "results.pkl"))

        table.to_csv(os.path.join(model_dir, "comparison.csv"), index=False)
    except Exception as exc:
        raise RuntimeError(f"Failed to save Model A results: {exc}") from exc
    print("\nModel comparison")
    print(table.to_string(index=False))
    return table


def main() -> None:
    """CLI entry point for Model A training."""
    parser = argparse.ArgumentParser(description="Train Model A traditional ML components.")
    parser.add_argument("--data-dir", default=os.path.join("data", "processed"))
    parser.add_argument("--model-dir", default=os.path.join("models", "model_a", "traditional"))
    parser.add_argument("--skip-slow", action="store_true")
    args = parser.parse_args()
    train_all(args.data_dir, args.model_dir, args.skip_slow)


if __name__ == "__main__":
    main()
